name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          if [ ! -d '${{ secrets.VPS_PATH }}' ]; then
            echo '🆕 Dossier non trouvé, on le crée et on clone le repo...'
            mkdir -p '${{ secrets.VPS_PATH }}'
            git clone https://github.com/${{ github.repository }} '${{ secrets.VPS_PATH }}'
          else
            echo '✅ Dossier existant, on continue...'
            cd '${{ secrets.VPS_PATH }}'
            git pull origin main
          fi
        "

    - name: Create .env file from secret
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          echo '${{ secrets.ENV_FILE }}' > '${{ secrets.VPS_PATH }}/.env'
        "

    - name: Run docker compose
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          cd '${{ secrets.VPS_PATH }}' && \
          docker compose down && \
          docker compose up -d --build
        "
